<ul class="c-box-time-line__content-list u-mt-30">
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-01" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">Production Supervisor</span></a></li>
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-02" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">Sales Manager (สามย่าน กรุงเทพ)</span></a></li>
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-03" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">ผู้จัดการแผนกจัดซื้ออาวุโส</span></a></li>
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-04" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">Sales (ตลาดสด)</span></a></li>
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-05" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">หัวหน้าแผนกขนส่ง (บ้านนา)</span></a></li>
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-06" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">QC Supervisor</span></a></li>
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-07" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">เจ้าหน้าที่วิจัยและพัฒนาผลิตภัณฑ์/เจ้าหน้าที่พัฒนาบรรจุภัณฑ์</span></a></li>
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-08" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">Sales (ชัยภูมิ)</span></a></li>
  <li class="c-box-time-line__content-list-item"><a class="modaal" href="#job-09" data-modaal-type="inline" data-modaal-animation="fade" data-modaal-overlay-opacity="0.9"><i class="fas fa-chevron-right"></i><span class="text">ผู้จัดการฝ่ายทรัพยากรบุคคล</span></a></li>
</ul>